function G = UR5e_G(in1)
%UR5e_G
%    G = UR5e_G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    26-Jul-2026 00:21:49

theta2 = in1(2,:);
theta3 = in1(3,:);
theta4 = in1(4,:);
theta5 = in1(5,:);
t2 = sin(theta5);
t3 = theta2+theta3;
t4 = cos(t3);
t5 = t3+theta4;
t6 = cos(t5);
t7 = sin(t5);
t8 = t4.*-1.8439152642e+1;
t10 = t7.*1.825114203;
t11 = t2.*t6.*-5.6086678665e-1;
G = [0.0;t8+t10+t11-cos(theta2).*4.13172675e+1;t8+t10+t11;t10+t11;t7.*cos(theta5).*-5.6086678665e-1;0.0];
end
