function G_box = UR5e_payload_G(in1,box_mass)
%UR5e_payload_G
%    G_box = UR5e_payload_G(IN1,BOX_MASS)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    26-Jul-2026 21:49:36

theta2 = in1(2,:);
theta3 = in1(3,:);
theta4 = in1(4,:);
theta5 = in1(5,:);
t2 = sin(theta5);
t3 = theta2+theta3;
t4 = cos(t3);
t5 = t3+theta4;
t6 = cos(t5);
t7 = sin(t5);
t8 = t4.*3.922e-1;
t9 = t7.*-9.97e-2;
t10 = t7.*9.97e-2;
t11 = t2.*t6.*4.96e-2;
G_box = [0.0;box_mass.*(t8+t9+t11+cos(theta2).*4.25e-1).*-9.81;box_mass.*(t8+t9+t11).*-9.81;box_mass.*(t10-t11).*9.81;box_mass.*t7.*cos(theta5).*-4.86576e-1;0.0];
end
